services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      CONFIG_PORT: ${CONFIG_PORT}
      EMAIL: ${EMAIL}
    ports:
      - "443:443"
    expose:
      - "2053"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.3x-ui.rule=Host(`aeza.elmir-kuba.ru`)"
      - "traefik.http.routers.3x-ui.entrypoints=websecure"
      - "traefik.http.routers.3x-ui.tls=true"
      - "traefik.http.routers.3x-ui.tls.certresolver=myresolver"
      - "traefik.http.services.3x-ui.loadbalancer.server.port=2053"
    restart: unless-stopped

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped
